version: "3.8"

services:

    portfolio_old-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: portfolio_old-backend
        env_file:
            - backend/.env
        restart: unless-stopped
        ports:
            -   "5005:5005"
        networks:
            - portfolio_old-network

networks:
    bridge:
        driver: portfolio_old-network