version: "3.8"

services:

    portfolio_old-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: portfolio_old-backend
        restart: unless-stopped
        ports:
            -   "5005:5005"
        networks:
            -   nginx_network
            -   portfolio_old_default

networks:
    nginx_network:
        external: true
    portfolio_old_default: