version: "3.8"

services:

    portfolio-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: portfolio-nginx
        restart: unless-stopped
        ports:
                -   "80:80"
                -   "443:443"
        networks:
            -   nginx_network
            -   portfolio_network
        volumes:
            -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    portfolio-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: portfolio-backend
        restart: unless-stopped
        ports:
            -   "5000:5000"
        networks:
            -   nginx_network
            -   portfolio_network

networks:
    nginx_network:
        external: true
    portfolio_network: