version: "3.8"

services:

        nginx:
            image: nginx:alpine
            restart: unless-stopped
            volumes:
                -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            ports:
                -   80:80
            networks:
                -   default
                -   portfolio
            depends_on:
                -   portfolio-backend

        portfolio-backend:
            build:
                context: backend
                dockerfile: Dockerfile
            container_name: portfolio-backend
            networks:
                portfolio:
                    aliases:
                        -   portfolio-backend

networks:
    portfolio: