version: "3.8"

services:

    portfolio-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: portfolio-backend
        restart: unless-stopped
        ports:
            -   "5000:5000"
        networks:
            -   nginx_network
            -   portfolio_network

networks:
    nginx_network:
        external: true
    portfolio_network: