version: "3.8"

services:
        portfolio-backend:
            build:
                context: backend
                dockerfile: Dockerfile
            container_name: portfolio-backend
            networks:
                portfolio:
                    aliases:
                        -   portfolio-backend

networks:
    portfolio: